server.port = 8085
logging.file.name=Logging_file.log
uspto.userFilePath=E:/Projects/PTO/users/users/user.csv
uspto.serverURL=http://localhost:9999
uspto.activitiURL=/activiti-app/api/
uspto.userName=admin@app.activiti.com
uspto.password=admin
